modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT"

 issueTrackerURL="https://github.com/nanite/ItShallNotTick/issues" #optional

[[mods]]
modId = "itshallnottick"
version = "${version}"
displayName = "It Shall Not Tick"
 logoFile="icon.png" #optional
 displayURL="https://www.curseforge.com/minecraft/mc-mods/it-shall-not-tick" #optional
 credits="Mikey" #optional
 authors="Me! (Gaz492)" #optional
description = '''
It Shall Not Tick (ISNT) is a performance enhancing mod that limits entity ticking to within a configurable range of players.
'''

[[dependencies.itshallnottick]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.itshallnottick]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"