name: Build & Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Build & release to curseforge
        env:
          GIT_COMMIT: ${{ github.event.after }}
          GIT_PREVIOUS_COMMIT: ${{ github.event.before }}
          NANITE_DEPLOY : ${{ secrets.NANITE_DEPLOY  }}
          CURSE_DEPLOY: ${{ secrets.CURSE_DEPLOY }}
        run: |
          chmod +x ./gradlew
          ./gradlew build publish curseforge --stacktrace --no-daemon
      - name: Release to Github
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          body_path: ./CHANGELOG.md
          files: build/libs/*.jar